import numpy as np
from matplotlib import pyplot as plt
import scipy
from scipy import interpolate 

#All tests are done for the following cosmology: flat LCDM with Omega_c=0.25
#Omega_b=0.05, h=0.7, A_s=2.1e-9, n_s=0.96

#CLASS runs
ps_lin_class_z0=np.loadtxt('ccl_linear_z0_pk.dat',skiprows=4)
ps_nonlin_class_z0=np.loadtxt('ccl_halofit_z0_pk.dat',skiprows=4)
ps_lin_class_z3=np.loadtxt('ccl_linear_z3_pk.dat',skiprows=4)
ps_nonlin_class_z3=np.loadtxt('ccl_halofit_z3_pk.dat',skiprows=4)

#Plot CLASS outputs - sanity check
plt.figure(figsize=(7,6))
plt.gca().set_xscale('log')
plt.gca().set_yscale('log')
plt.plot(ps_lin_class_z0[:,0],ps_lin_class_z0[:,1],'k-',label='Linear, $z=0$')
plt.plot(ps_lin_class_z3[:,0],ps_lin_class_z3[:,1],'r-',label='Linear, $z=3$')
plt.plot(ps_nonlin_class_z0[:,0],ps_nonlin_class_z0[:,1],'k--',label='NLinear, $z=0$')
plt.plot(ps_nonlin_class_z3[:,0],ps_nonlin_class_z3[:,1],'r--',label='NLinear, $z=3$')
plt.xlim(xmin=1e-5,xmax=200)
plt.legend(loc='upper right',prop={'size':10})
plt.xlabel(r'$k$ [h/Mpc]',fontsize=20)
plt.ylabel(r'$P_{fid}$ [(Mpc/h)$^3$]',fontsize=22)
plt.title(r'CLASS',fontsize=22)
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
plt.savefig('justclass.eps')
plt.clf()

#Fiducial means K_MAX_SPLINE=50, K_MAX=1e3, deltak=1e-2
#Files have 3 columns: k [h/Mpc], P(k,z=0), P(k,z=3) [(Mpc/h)^3]
ps_lin_fiduc=np.loadtxt('PSlin_fiduc',skiprows=1)
ps_nonlin_fiduc=np.loadtxt('PSnonlin_fiduc',skiprows=1)
#kms5e3 means K_MAX_SPLINE=5e3, K_MAX=1e3
ps_lin_kms5e3=np.loadtxt('PSlin_kms5e3',skiprows=1)
ps_nonlin_kms5e3=np.loadtxt('PSnonlin_kms5e3',skiprows=1)
#kms5e2 means K_MAX_SPLINE=500, K_MAX=1e3
ps_lin_kms5e2=np.loadtxt('PSlin_kms5e2',skiprows=1)
ps_nonlin_kms5e2=np.loadtxt('PSnonlin_kms5e2',skiprows=1)
#kms50_dk1eminus4 means K_MAX_SPLINE=50, K_MAX=1e3, deltak=1.e-4
ps_lin_kms50_dk1eminus4=np.loadtxt('PSlin_kms50_dk1eminus4',skiprows=1)
ps_nonlin_kms50_dk1eminus4=np.loadtxt('PSnonlin_kms50_dk1eminus4',skiprows=1)

plt.figure(figsize=(12,5))
plt.subplot(1,2,1)
plt.plot(ps_lin_fiduc[:,0],abs(ps_lin_fiduc[:,1]/ps_lin_class_z0[:,1]-1.),'k--',label=r'K_MAX_SPLINE$=50$/Mpc, $\Delta\ln k=10^{-2}$')
plt.plot(ps_lin_fiduc[:,0],abs(ps_lin_kms5e2[:,1]/ps_lin_class_z0[:,1]-1.),'k-',label=r'K_MAX_SPLINE$=500$/Mpc, $\Delta\ln k=10^{-2}$')
#plt.plot(ps_lin_fiduc[:,0],abs(ps_lin_kms5e3[:,1]/ps_lin_class_z0[:,1]-1.),'k:',label=r'K_MAX_SPLINE$=5000$/Mpc, $\Delta\ln k=10^{-2}$')
plt.plot(ps_lin_fiduc[:,0],abs(ps_lin_kms50_dk1eminus4[:,1]/ps_lin_class_z0[:,1]-1.),'m-',label=r'K_MAX_SPLINE$=50$/Mpc, $\Delta\ln k=10^{-4}$')
plt.gca().set_xscale('log')
plt.gca().set_yscale('log')
plt.xlim(xmin=0.01,xmax=200)
#plt.legend(loc='upper left',prop={'size':10})
plt.xlabel(r'$k$ [h/Mpc]',fontsize=20)
plt.ylabel(r'$\Delta P/P_{fid}$',fontsize=22)
plt.title(r'Linear, $z=0$',fontsize=22)
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
plt.subplot(1,2,2)
plt.plot(ps_lin_fiduc[:,0],abs(ps_lin_fiduc[:,2]/ps_lin_class_z3[:,1]-1.),'k--',label=r'K_MAX_SPLINE$=50$/Mpc, $\Delta\ln k=10^{-2}$')
plt.plot(ps_lin_fiduc[:,0],abs(ps_lin_kms5e2[:,2]/ps_lin_class_z3[:,1]-1.),'k-',label=r'K_MAX_SPLINE$=500$/Mpc, $\Delta\ln k=10^{-2}$')
#plt.plot(ps_lin_fiduc[:,0],abs(ps_lin_kms5e3[:,2]/ps_lin_class_z3[:,1]-1.),'k:',label=r'K_MAX_SPLINE$=5000$/Mpc, $\Delta\ln k=10^{-2}$')
plt.plot(ps_lin_fiduc[:,0],abs(ps_lin_kms50_dk1eminus4[:,2]/ps_lin_class_z3[:,1]-1.),'m-',label=r'K_MAX_SPLINE$=50$/Mpc, $\Delta\ln k=10^{-4}$')
plt.gca().set_xscale('log')
plt.gca().set_yscale('log')
plt.xlim(xmin=0.01,xmax=200)
plt.xlabel('$k$ [h/Mpc]',fontsize=24)
plt.title(r'Linear, $z=3$',fontsize=22)
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
plt.tight_layout()
plt.savefig('PS_converge_lin.eps')
plt.clf()


plt.figure(figsize=(12,5))
plt.subplot(1,2,1)
plt.plot(ps_nonlin_fiduc[:,0],abs(ps_nonlin_fiduc[:,1]/ps_nonlin_class_z0[:,1]-1.),'k--',label=r'K_MAX_SPLINE$=50$/Mpc, $\Delta\ln k=10^{-2}$')
plt.plot(ps_nonlin_fiduc[:,0],abs(ps_nonlin_kms5e2[:,1]/ps_nonlin_class_z0[:,1]-1.),'k-',label=r'K_MAX_SPLINE$=500$/Mpc, $\Delta\ln k=10^{-2}$')
#plt.plot(ps_nonlin_fiduc[:,0],abs(ps_nonlin_kms5e3[:,1]/ps_nonlin_class_z0[:,1]-1.),'k:',label=r'K_MAX_SPLINE$=5000$/Mpc, $\Delta\ln k=10^{-2}$')
plt.plot(ps_nonlin_fiduc[:,0],abs(ps_nonlin_kms50_dk1eminus4[:,1]/ps_nonlin_class_z0[:,1]-1.),'m-',label=r'K_MAX_SPLINE$=50$/Mpc, $\Delta\ln k=10^{-4}$')
plt.gca().set_xscale('log')
plt.gca().set_yscale('log')
plt.xlim(xmin=0.01,xmax=200)
plt.ylim(ymin=1e-7,ymax=1)
plt.legend(loc='upper left',prop={'size':12})
plt.xlabel(r'$k$ [h/Mpc]',fontsize=24)
plt.ylabel(r'$\Delta P/P_{fid}$',fontsize=22)
plt.title(r'Non-linear, $z=0$',fontsize=22)
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
plt.subplot(1,2,2)
plt.plot(ps_nonlin_fiduc[:,0],abs(ps_nonlin_fiduc[:,2]/ps_nonlin_class_z3[:,1]-1.),'k--',label=r'K_MAX_SPLINE$=50$/Mpc, $\Delta\ln k=10^{-2}$')
plt.plot(ps_nonlin_fiduc[:,0],abs(ps_nonlin_kms5e2[:,2]/ps_nonlin_class_z3[:,1]-1.),'k-',label=r'K_MAX_SPLINE$=500$/Mpc, $\Delta\ln k=10^{-2}$')
#plt.plot(ps_nonlin_fiduc[:,0],abs(ps_nonlin_kms5e3[:,2]/ps_nonlin_class_z3[:,1]-1.),'k:',label=r'K_MAX_SPLINE$=5000$/Mpc, $\Delta\ln k=10^{-2}$')
plt.plot(ps_nonlin_fiduc[:,0],abs(ps_nonlin_kms50_dk1eminus4[:,2]/ps_nonlin_class_z3[:,1]-1.),'m-',label=r'K_MAX_SPLINE$=50$/Mpc, $\Delta\ln k=10^{-4}$')
plt.gca().set_xscale('log')
plt.gca().set_yscale('log')
plt.xlim(xmin=0.01,xmax=200)
plt.ylim(ymin=1e-7,ymax=1)
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
plt.xlabel('$k$ [h/Mpc]',fontsize=24)
plt.title(r'Non-linear, $z=3$',fontsize=22)
plt.tight_layout()
plt.savefig('PS_converge_nonlin.eps')
plt.clf()


#Check nk=5000 instead of 1000
ps_lin_nk5000=np.loadtxt('PSlin_nk5000',skiprows=1)
ps_nonlin_nk5000=np.loadtxt('PSnonlin_nk5000',skiprows=1)
plt.figure(figsize=(12,5))
plt.subplot(121)
plt.gca().set_xscale('log')
plt.gca().set_yscale('log')
plt.xlim(xmin=0.01,xmax=200)
plt.ylim(ymin=1e-7,ymax=1)
plt.legend(loc='upper left',prop={'size':12})
plt.xlabel(r'$k$ [h/Mpc]',fontsize=24)
plt.ylabel(r'$\Delta P/P_{fid}$',fontsize=22)
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
plt.title(r'Linear',fontsize=22)
plt.plot(ps_lin_fiduc[:,0],abs(ps_lin_fiduc[:,1]/ps_lin_class_z0[:,1]-1.),'k-',label=r'Fiducial $z=0$')
plt.plot(ps_lin_fiduc[:,0],abs(ps_lin_nk5000[:,1]/ps_lin_class_z0[:,1]-1.),'k--',label=r'N_K=5000 $z=0$')
plt.plot(ps_lin_fiduc[:,0],abs(ps_lin_fiduc[:,2]/ps_lin_class_z3[:,1]-1.),'r-',label=r'Fiducial $z=3$')
plt.plot(ps_lin_fiduc[:,0],abs(ps_lin_nk5000[:,2]/ps_lin_class_z3[:,1]-1.),'r--',label=r'N_K=5000 $z=3$')
plt.subplot(122)
plt.plot(ps_lin_fiduc[:,0],abs(ps_nonlin_fiduc[:,1]/ps_nonlin_class_z0[:,1]-1.),'k-',label=r'NL Fiducial $z=0$')
plt.plot(ps_lin_fiduc[:,0],abs(ps_nonlin_nk5000[:,1]/ps_nonlin_class_z0[:,1]-1.),'k--',label=r'NL N_K=5000 $z=0$')
plt.plot(ps_lin_fiduc[:,0],abs(ps_nonlin_fiduc[:,2]/ps_nonlin_class_z3[:,1]-1.),'r-',label=r'NL Fiducial $z=3$')
plt.plot(ps_lin_fiduc[:,0],abs(ps_nonlin_nk5000[:,2]/ps_nonlin_class_z3[:,1]-1.),'r--',label=r'NL N_K=5000 $z=3$')
plt.gca().set_xscale('log')
plt.gca().set_yscale('log')
plt.xlim(xmin=0.01,xmax=200)
plt.ylim(ymin=1e-7,ymax=1)
plt.legend(loc='upper left',prop={'size':12})
plt.xlabel(r'$k$ [h/Mpc]',fontsize=24)
plt.ylabel(r'$\Delta P/P_{fid}$',fontsize=22)
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
plt.title(r'Non-linear',fontsize=22)
plt.tight_layout()
plt.savefig('PS_both_nk5000.eps')
plt.clf()


#Check na=200 instead of 50
ps_lin_na200=np.loadtxt('PSlin_na200_z1p034',skiprows=1)
ps_nonlin_na200=np.loadtxt('PSnonlin_na200_z1p034',skiprows=1)
ps_lin_z1p034=np.loadtxt('PSlin_fiduc_z1p034',skiprows=1)
ps_nonlin_z1p034=np.loadtxt('PSnonlin_fiduc_z1p034',skiprows=1)
plt.figure(figsize=(7,6))
plt.plot(ps_lin_fiduc[:,0],abs(ps_lin_na200[:,2]/ps_lin_z1p034[:,2]-1.),'k--',label=r'L N_A=200 $z=1.034$')
plt.plot(ps_lin_fiduc[:,0],abs(ps_nonlin_na200[:,2]/ps_nonlin_z1p034[:,2]-1.),'r--',label=r'NL N_A=20 $z=1.034$')
plt.gca().set_xscale('log')
plt.gca().set_yscale('log')
plt.xlim(xmin=0.01,xmax=200)
plt.ylim(ymin=1e-10,ymax=1e-4)
plt.legend(loc='upper left',prop={'size':12})
plt.xlabel(r'$k$ [h/Mpc]',fontsize=24)
plt.ylabel(r'$\Delta P/P_{fid}$',fontsize=22)
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
plt.savefig('PS_both_na200.eps')
plt.clf()



#Try bilinear splines:

#Fiducial means K_MAX_SPLINE=50, K_MAX=1e3, deltak=1e-2
#Files have 3 columns: k [h/Mpc], P(k,z=0), P(k,z=3) [(Mpc/h)^3]
ps_lin_fiduc=np.loadtxt('bilin/PSlin_fiduc',skiprows=1)
ps_nonlin_fiduc=np.loadtxt('bilin/PSnonlin_fiduc',skiprows=1)
#kms5e3 means K_MAX_SPLINE=5e3, K_MAX=1e3
ps_lin_kms5e3=np.loadtxt('bilin/PSlin_kms5e3',skiprows=1)
ps_nonlin_kms5e3=np.loadtxt('bilin/PSnonlin_kms5e3',skiprows=1)
#kms5e2 means K_MAX_SPLINE=500, K_MAX=1e3
ps_lin_kms5e2=np.loadtxt('bilin/PSlin_kms5e2',skiprows=1)
ps_nonlin_kms5e2=np.loadtxt('bilin/PSnonlin_kms5e2',skiprows=1)

plt.figure(figsize=(12,5))
plt.subplot(1,2,1)
plt.plot(ps_lin_fiduc[:,0],abs(ps_lin_fiduc[:,1]/ps_lin_class_z0[:,1]-1.),'k--',label=r'K_MAX_SPLINE$=50$/Mpc, $\Delta\ln k=10^{-2}$')
plt.plot(ps_lin_fiduc[:,0],abs(ps_lin_kms5e2[:,1]/ps_lin_class_z0[:,1]-1.),'k-',label=r'K_MAX_SPLINE$=500$/Mpc, $\Delta\ln k=10^{-2}$')
plt.gca().set_xscale('log')
plt.gca().set_yscale('log')
plt.xlim(xmin=0.01,xmax=200)
plt.legend(loc='upper left',prop={'size':10})
plt.xlabel(r'$k$ [h/Mpc]',fontsize=20)
plt.ylabel(r'$\Delta P/P_{fid}$',fontsize=22)
plt.title(r'Linear, $z=0$',fontsize=22)
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
plt.subplot(1,2,2)
plt.plot(ps_lin_fiduc[:,0],abs(ps_lin_fiduc[:,2]/ps_lin_class_z3[:,1]-1.),'k--',label=r'K_MAX_SPLINE$=50$/Mpc, $\Delta\ln k=10^{-2}$')
plt.plot(ps_lin_fiduc[:,0],abs(ps_lin_kms5e2[:,2]/ps_lin_class_z3[:,1]-1.),'k-',label=r'K_MAX_SPLINE$=500$/Mpc, $\Delta\ln k=10^{-2}$')
plt.gca().set_xscale('log')
plt.gca().set_yscale('log')
plt.xlim(xmin=0.01,xmax=200)
plt.xlabel('$k$ [h/Mpc]',fontsize=24)
plt.title(r'Linear, $z=3$',fontsize=22)
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
plt.tight_layout()
plt.savefig('PS_converge_lin_bilin.eps')
plt.clf()


plt.figure(figsize=(12,5))
plt.subplot(1,2,1)
plt.plot(ps_nonlin_fiduc[:,0],abs(ps_nonlin_fiduc[:,1]/ps_nonlin_class_z0[:,1]-1.),'k--',label=r'K_MAX_SPLINE$=50$/Mpc, $\Delta\ln k=10^{-2}$')
plt.plot(ps_nonlin_fiduc[:,0],abs(ps_nonlin_kms5e2[:,1]/ps_nonlin_class_z0[:,1]-1.),'k-',label=r'K_MAX_SPLINE$=500$/Mpc, $\Delta\ln k=10^{-2}$')
plt.gca().set_xscale('log')
plt.gca().set_yscale('log')
plt.xlim(xmin=0.01,xmax=200)
plt.ylim(ymin=1e-7,ymax=1)
plt.legend(loc='upper left',prop={'size':12})
plt.xlabel(r'$k$ [h/Mpc]',fontsize=24)
plt.ylabel(r'$\Delta P/P_{fid}$',fontsize=22)
plt.title(r'Non-linear, $z=0$',fontsize=22)
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
plt.subplot(1,2,2)
plt.plot(ps_nonlin_fiduc[:,0],abs(ps_nonlin_fiduc[:,2]/ps_nonlin_class_z3[:,1]-1.),'k--',label=r'K_MAX_SPLINE$=50$/Mpc, $\Delta\ln k=10^{-2}$')
plt.plot(ps_nonlin_fiduc[:,0],abs(ps_nonlin_kms5e2[:,2]/ps_nonlin_class_z3[:,1]-1.),'k-',label=r'K_MAX_SPLINE$=500$/Mpc, $\Delta\ln k=10^{-2}$')
plt.gca().set_xscale('log')
plt.gca().set_yscale('log')
plt.xlim(xmin=0.01,xmax=200)
plt.ylim(ymin=1e-7,ymax=1)
plt.xticks(fontsize=14)
plt.yticks(fontsize=14)
plt.xlabel('$k$ [h/Mpc]',fontsize=24)
plt.title(r'Non-linear, $z=3$',fontsize=22)
plt.tight_layout()
plt.savefig('PS_converge_nonlin_bilin.eps')
plt.clf()


exit()
